Add mint NFT endpoint and sample curl request
solana-labs/chatgpt-plugin pull request #38
Opened 2023-07-27 16:54 UTC by govarun

2023-07-27 16:57 UTC, ngundotra requested changes
Good progress! Please make this a draft PR until you think it's ready for review.

2023-07-27 16:57 UTC, ngundotra commented on chatgpt-plugin/src/pages/api/handlers/solana-pay/sign/createMintNFT.ts
> +          .serialize({ requireAllSignatures: true })
This should be false

2023-07-27 16:57 UTC, ngundotra commented on chatgpt-plugin/src/pages/api/handlers/solana-pay/sign/testCreateMintNFT.sh
> +curl --location 'localhost:3000/api/handlers/solana-pay/sign/createMintNFT?=null' \
Please remove this file, and instead provide the curl as a comment for now. 

Let's add tests for this in a separate PR

2023-07-27 17:59 UTC, ngundotra commented on chatgpt-plugin/src/pages/api/handlers/solana-pay/sign/testCreateMintNFT.sh
> +curl --location 'localhost:3000/api/handlers/solana-pay/sign/createMintNFT?=null' \
@govarun please provide the curl command in the description of this PR, instead of comment. My bad.

2023-07-31 18:17 UTC, govarun commented
curl --location 'localhost:3000/api/handlers/solana-pay/sign/createMintNFT?=null' \
--header 'Content-Type: application/json' \
--data '{
    "name": "test first AI minted NFT",
    "account":"8rcvXRDktcqzNZ9N1iDAptYky93HuZvbzs76ZFXPmKQs",
    "metadataUri":"https://arweave.net/9XciS8hnBhf1PLf7B1zlUEP_cLiQQ9Zu8xiKV5hd7rc",
    "sellerFee":250
}'

2023-07-31 20:35 UTC, ngundotra commented on chatgpt-plugin/src/pages/api/handlers/solana-pay/sign/createNftCollection.ts
> +    tx.partialSign(payerPublicKey);
Partial sign with the `mint` `Keypair` instead

2023-07-31 20:41 UTC, ngundotra commented on chatgpt-plugin/src/pages/api/handlers/solana-pay/sign/createNftCollection.ts
> +  );
should be creating an instruction to create an associated token account using:
https://solana-labs.github.io/solana-program-library/token/js/functions/createAssociatedTokenAccountIdempotentInstruction.html

2023-08-07 17:27 UTC, ngundotra commented on chatgpt-plugin/src/pages/api/handlers/metaplex/createNFTCollection/src/main.ts
> +import { Keypair, PublicKey } from "@solana/web3.js";
If this is a one-off script, move this to `scripts/` and rename the file

2023-08-07 17:30 UTC, ngundotra commented on chatgpt-plugin/src/pages/api/handlers/metaplex/createNFTCollection/assets/chatgpt-collection-logo.png
Nice logo! If this is only used in the collection minting script, please move to root folder under `assets/` folder or something :)

2023-08-16 03:34 UTC, closed without merging

2023-08-16 03:35 UTC, govarun commented
The changes are in another branch, and in a better compiled pull request. #51